---

s3fs_git_repo: https://github.com/s3fs-fuse/s3fs-fuse.git
s3fs_source_path: /opt/s3fs-fuse

s3fs_mount_max: "1000"
s3fs_user_allow_other: true

s3fs_passwd_path: /etc/passwd-s3fs

s3fs:
  accessKeyId: "accessKeyId"
  secretAccessKey: "secretAccessKey"
  buckets:
    - localmount: /mnt/s3fs
      bucketname: aws.bucket.name
      options: "allow_other,use_cache=/tmp,max_stat_cache_size=100000,uid=33,gid=33,umask=002"
