---

- name: S3FS | Ensure endpoint exist
  file:
    path: "{{ item.localmount }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items: "{{ s3fs.buckets }}"

- name: S3FS | Deploy AWS access key
  template:
    src: etc/passwd-s3fs.j2
    dest: "{{ s3fs_passwd_path }}"
    owner: root
    group: root
    mode: 0640

- name: S3FS | Configure fstab and mount bucket
  mount:
    name: "{{ item.localmount }}"
    src: "{{ item.bucketname }}"
    fstype: fuse
    opts: "{{ item.options }},passwd_file={{ s3fs_passwd_path }}"
    state: present
  with_items: "{{ s3fs.buckets }}"
